# Generated by Django 3.2.7 on 2022-06-12 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_teacher',
            new_name='is_staff',
        ),
    ]
